name: Release main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: release-${{ steps.date.outputs.date }}
          RELEASE_NAME: release-${{ steps.date.outputs.date }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          TAG_NAME: release-${{ steps.date.outputs.date }}
          RELEASE_NAME: release-${{ steps.date.outputs.date }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $TAG_NAME
          release_name: $RELEASE_NAME
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
