name: Release main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: release-${{ steps.current-time.outputs.time }}
          RELEASE_NAME: release-${{ steps.current-time.outputs.time }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          TAG_NAME: release-${{ steps.current-time.outputs.time }}
          RELEASE_NAME: release-${{ steps.current-time.outputs.time }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
