name: Release main
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-$(date +'%Y%m%dT%H%M%S')
          release_name: Release $(date +'%Y%m%dT%H%M%S')
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
